#!/usr/bin/env python3

import sys
import json
import urllib.request

def request(action, **params):
    return {'action': action, 'params': params, 'version': 6}

def invoke(action, **params):
    requestJson = json.dumps(request(action, **params)).encode('utf-8')
    response = json.load(urllib.request.urlopen(urllib.request.Request('http://localhost:8765', requestJson)))
    if len(response) != 2:
        raise Exception('response has an unexpected number of fields')
    if 'error' not in response:
        raise Exception('response is missing required error field')
    if 'result' not in response:
        raise Exception('response is missing required result field')
    if response['error'] is not None:
        raise Exception(response['error'])
    return response['result']

# invoke('createDeck', deck='test1')
# result = invoke('deckNames')
# print('got list of decks: {}'.format(result))

if __name__ == '__main__':
    if len(sys.argv) > 1:
        action = sys.argv[1]
        if len(sys.argv) > 2:
            params = sys.argv[2:]
            arg_dict = dict(arg.split('=') for arg in sys.argv[2:])
            for key, value in arg_dict.items():
                if key == "decks":
                    arg_dict[key] = value.split(" ")
            results = invoke(action, **arg_dict)
        else:
            results = invoke(action)
    else:
        results = invoke('deckNames')
    print(results)
