#!/usr/bin/env bash

pdf_file="$1"
pdftohtml_dir=$HOME/pipes/pdftohtml

# rm -rf $pdftohtml_dir/*

pdftohtml -noframes -nomerge -s -c -q -zoom 2.1 -wbt 10000 -enc UTF-8 "$pdf_file" $pdftohtml_dir/1.html

caddy file-server --root ~ --listen :2015 & browsh --firefox.with-gui --startup-url http://localhost:2015/pipes/pdftohtml/1.html
