#!/usr/bin/env bash

version=$(curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r .tag_name)

# if the repo doesn't utilise GitHub releases, get the latest tag
if [ "$version" == "null" ]; then
    version=$(curl --silent "https://api.github.com/repos/$1/tags" | jq -r '.[0].name')
fi

sed "s/^v//" <<< $version

# echo $version
