#!/usr/bin/env bash

# get_h: extract C like function declarations for header file 

# Find function name lines (return type followed by paratheses and left curly brace), and then replace left curly brace with semicolon
sed -n '
/^[[:alnum:]_][[:alnum:]_]* .*(.*) *{/s/(.*) *{.*/();/p
/^typedef .*{/,/^}.*;/p
' "$@"
