#!/usr/bin/env bash

# View the images of first 10 pages of pdf in terminal using tiv

img_dir=~/pipes/pdf_img

rm $img_dir/*

pdftoppm "$1" -jpeg -f 1 -l 10 -rx 500 -ry 500 $img_dir/img

for img_file in $img_dir/*.jpg; do
	tiv $img_file
done

tiv $img_dir/*.jpg
