#!/usr/bin/env bash

# Download video file using youtube-dl
# Prefer mp4 format for better compatibility with various ios app

# Use socks5 proxy
# export https_proxy=socks5://127.0.0.1:1080
# export http_proxy=socks5://127.0.0.1:1080

url_file="$1"

youfile $url_file && to_mp4 mkv
