#!/usr/bin/env bash

# Download video file using youtube-dl

# Use socks5 proxy
export https_proxy=socks5://127.0.0.1:1080
export http_proxy=socks5://127.0.0.1:1080

url_file="$1"
# Parallelism can be already be delegated to xargs -P x -n y where x is the number of parallel downloads and y is the number of URLs/IDs to pass to youtube-dl, most likely 1. 
n=0
until [ $n -ge 10 ]
do
	youtube-dl -ciw --write-sub --write-auto-sub "$url_file" && break
	n=$((n+1))
	sleep 15
done
