#!/usr/bin/env bash

# Download music using youtube-dl

# Use socks5 proxy
# export https_proxy=socks5://127.0.0.1:1080
# export http_proxy=socks5://127.0.0.1:1080

yt-dlp --extract-audio --audio-format mp3 "$1"
